# Generated by Django 5.2.7 on 2025-11-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comands', '0005_remove_command_members_teammember'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='command',
        ),
        migrations.AddField(
            model_name='project',
            name='commands',
            field=models.ManyToManyField(related_name='projects', to='comands.command'),
        ),
    ]
