# Generated by Django 5.2.7 on 2025-10-10 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comands', '0002_alter_command_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='team',
        ),
        migrations.AddField(
            model_name='command',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='team_comand', to=settings.AUTH_USER_MODEL),
        ),
    ]
