# Generated by Django 5.2.7 on 2025-10-10 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comands', '0003_remove_command_team_command_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='team',
        ),
        migrations.AddField(
            model_name='command',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='commands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='command',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_commands', to=settings.AUTH_USER_MODEL),
        ),
    ]
